name: AnnihilationDW
author: BenRush
version: 3.1.7
main: com.drizzard.annihilationdw.Main
commands:
    drizzardwars:
        description: main command
        aliases: [dw]
        usage: /<command>
    vote:
        description: Used to vote for map
        aliases: [votar]
        usage: /<command>
    party:
        description: Create party
        usage: /<command>
#    points:
#        description: Manage points
#        aliases: [point, pts]
#        usage: /<command>
    help:
        description: Get Help
        usage: /<command>
    ability:
        description: Select ability
        aliases: [ab, abilities]
        usage: /<command>
permissions:
    dw.*:
        default: op
        description: Grants all permissions
        children:
            dw.vip: true
            dw.spectator: true
            dw.chance: true
            dw.party: true
    dw.vip:
        default: op
        description: Grants VIP permissions
    dw.spectator:
        default: op
        description: Can spectate full games
    dw.chance:
        default: op
        description: Gives a chance to join full game when someone leaves
        children:
            dw.spectator: true
    dw.party:
        default: op
        description: Gives access to create a party
    dw.changekit:
        default: op
        description: Gives access to change kit in middle of game
    dw.statsigns:
        default: op
        description: Gives access to create/destroy statistic signs